#!/usr/bin/env bash
# ============================================================================
# SmartAIAudit — Interactive Setup Wizard
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo ""
echo "==========================================="
echo "  SmartAIAudit Deployment Setup"
echo "==========================================="
echo ""

# --- Check prerequisites ---
for cmd in docker; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd is required but not installed." >&2
    exit 1
  fi
done

# Check docker compose (v2 plugin or standalone)
if docker compose version &>/dev/null; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  echo "ERROR: docker compose is required but not installed." >&2
  exit 1
fi

# --- Step 1: Cloud or self-hosted? ---
echo "How will you run Supabase?"
echo "  1) Cloud Supabase (supabase.com — recommended)"
echo "  2) Self-hosted (Docker containers on this machine)"
echo ""
read -rp "Choice [1]: " SUPABASE_MODE
SUPABASE_MODE="${SUPABASE_MODE:-1}"

SELFHOSTED=false
if [ "$SUPABASE_MODE" = "2" ]; then
  SELFHOSTED=true
fi

# --- Step 2: Collect credentials ---
echo ""
echo "--- Required Credentials ---"
echo ""

if [ "$SELFHOSTED" = true ]; then
  read -rp "PostgreSQL password (new): " POSTGRES_PASSWORD
  if [ -z "$POSTGRES_PASSWORD" ]; then
    POSTGRES_PASSWORD=$(openssl rand -hex 16)
    echo "  Auto-generated: $POSTGRES_PASSWORD"
  fi
fi

read -rp "Supabase Project URL: " SUPABASE_PROJECT_URL
read -rp "Supabase Publishable API Key (sb_publishable_...): " SUPABASE_PUBLISHABLE_API_KEY
read -rp "Supabase Secret Key (sb_secret_...): " SUPABASE_SECRET_KEY
echo ""
read -rp "OpenRouter API Key (sk-or-v1-...): " OPENROUTER_API_KEY

# Auto-generate security keys
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
echo ""
echo "Auto-generated JWT_SECRET and ENCRYPTION_KEY."

read -rp "CORS allowed origins [http://localhost:3000]: " CORS_ORIGIN
CORS_ORIGIN="${CORS_ORIGIN:-http://localhost:3000}"

read -rp "Backend port [8080]: " PORT
PORT="${PORT:-8080}"

# --- Step 3: Write .env ---
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_ENV=production
PORT=$PORT
CORS_ORIGIN=$CORS_ORIGIN

JWT_SECRET=$JWT_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY

SUPABASE_PROJECT_URL=$SUPABASE_PROJECT_URL
SUPABASE_PUBLISHABLE_API_KEY=$SUPABASE_PUBLISHABLE_API_KEY
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY

OPENROUTER_API_KEY=$OPENROUTER_API_KEY
OPENROUTER_MODEL_SMALL=google/gemini-3-flash-preview
OPENROUTER_MODEL_LARGE=google/gemini-3-pro-preview

LOG_LEVEL=info
EOF

if [ "$SELFHOSTED" = true ]; then
  cat >> "$ENV_FILE" <<EOF

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
EOF
fi

echo ""
echo "Wrote $ENV_FILE"

# --- Step 4: Start services ---
echo ""
echo "Starting services..."

cd "$SCRIPT_DIR"

if [ "$SELFHOSTED" = true ]; then
  $COMPOSE -f docker-compose.yml -f docker-compose.selfhosted.yml --profile supabase up -d --build
else
  $COMPOSE up -d --build
fi

# --- Step 5: Run migrations (self-hosted only) ---
if [ "$SELFHOSTED" = true ]; then
  echo ""
  echo "Waiting for database to be ready..."
  sleep 5

  MIGRATIONS_DIR="$SCRIPT_DIR/../../supabase/migrations"
  if [ -d "$MIGRATIONS_DIR" ]; then
    echo "Running database migrations..."
    for f in "$MIGRATIONS_DIR"/*.sql; do
      echo "  Applying $(basename "$f")..."
      docker exec -i "$(docker compose ps -q supabase-db)" \
        psql -U postgres -d postgres < "$f" 2>/dev/null || true
    done
    echo "Migrations applied."
  else
    echo "WARNING: No migrations directory found at $MIGRATIONS_DIR"
    echo "You will need to apply database migrations manually."
  fi
fi

# --- Step 6: Print access info ---
echo ""
echo "==========================================="
echo "  SmartAIAudit is running!"
echo "==========================================="
echo ""
echo "  Backend API:  http://localhost:$PORT"
echo "  Health check: http://localhost:$PORT/health"
echo "  WebSocket:    ws://localhost:$PORT/ws"
echo ""
echo "  Configure your Electron desktop apps with:"
echo "    VITE_BACKEND_URL=http://<this-server>:$PORT"
echo "    VITE_BACKEND_WS_URL=ws://<this-server>:$PORT"
echo ""
echo "  Logs: $COMPOSE logs -f backend"
echo ""
